name: Build and Publish Docker Image

# Event triggers for the workflow
on:
  push:
    branches:
      - main
  # Allows run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        # Checkout the repository to the runner
      - name: Checkout repository
        uses: actions/checkout@v2

        # Buildx is a CLI tool for building and testing Docker images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

        # Log in to Docker Hub using the username and password stored in GitHub Secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

        # Build and push the Docker image to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .    # The path to the Dockerfile (current directory)
          push: true    # Push the image to Docker Hub
          tags: ${{ secrets.DOCKER_USERNAME }}/gh-actions-docker:latest